config/routes.rb
Rails.application.routes.draw do
  

  resources :images do
    collection do
      get :result
    end
  end

  root 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)


  
  resources :exports do
    collection do
      get :event
    end
  end

  resources :slides
  resources :releases
  resources :events
  resources :tips
  resources :settings

  resources :whatsnews

  resources :layouts
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/settings_controller.rb
class SettingsController < InheritedResources::Base
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :healthy_tip_layout %><br>
    <%= f.text_field :healthy_tip_layout %>
  </div>
  <div class="field">
    <%= f.label :healthy_tip_archive_layout %><br>
    <%= f.text_field :healthy_tip_archive_layout %>
  </div>
  <div class="field">
    <%= f.label :in_the_news_layout %><br>
    <%= f.text_field :in_the_news_layout %>
  </div>
  <div class="field">
    <%= f.label :in_the_news_archive_layout %><br>
    <%= f.text_field :in_the_news_archive_layout %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Listing settings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Healthy tip layout</th>
      <th>Healthy tip archive layout</th>
      <th>In the news layout</th>
      <th>In the news archive layout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.name %></td>
        <td><%= setting.healthy_tip_layout %></td>
        <td><%= setting.healthy_tip_archive_layout %></td>
        <td><%= setting.in_the_news_layout %></td>
        <td><%= setting.in_the_news_archive_layout %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @setting.name %>
</p>

<p>
  <strong>Healthy tip layout:</strong>
  <%= @setting.healthy_tip_layout %>
</p>

<p>
  <strong>Healthy tip archive layout:</strong>
  <%= @setting.healthy_tip_archive_layout %>
</p>

<p>
  <strong>In the news layout:</strong>
  <%= @setting.in_the_news_layout %>
</p>

<p>
  <strong>In the news archive layout:</strong>
  <%= @setting.in_the_news_archive_layout %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>