config/routes.rb
Rails.application.routes.draw do
  

  resources :images do
    collection do
      get :result
    end
  end

  root 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)


  
  resources :exports do
    collection do
      get :event
    end
  end

  resources :slides
  resources :releases
  resources :events
  resources :tips
  resources :settings

  resources :whatsnews

  resources :layouts
end

app/models/whatsnew.rb
class Whatsnew < ActiveRecord::Base
  # has_many :exports
  belongs_to :layout
  belongs_to :admin_user

  after_save :generate_whats_new_content
  after_save :generate_whats_new

  after_destroy :generate_whats_new_content
  after_destroy :generate_whats_new
  acts_as_list add_new_at: :top

  enum status: { archive: 1, nonarchive: 0}

  scope :archived, -> { where(status: 1) }
  scope :active, -> { where(status: 0) }


	def generate_whats_new
		File.open('default_third_column_home' + '.html', "w") do |f|     
			n = Nokogiri::HTML(open("https://s3-us-west-2.amazonaws.com/hhcheroku/uploads/whatsnew_content.html"))
				layout = Layout.find_by(layout_name: "What's New?")			
				f.write(
					layout.body_top + "\n""\n""\n" +
					n.css('div.contentdiv').to_s + "\n""\n""\n" +
					layout.body_bottom
					)
			uploader = FileUploader.new
      		uploader.store_dir = "repo/hhc-corp/includes/content/column_modules"
			uploader.store!(f)
		end     			
	end


	def generate_whats_new_content
		File.open('whatsnew_content' + '.html', "w") do |f|     
				
				Whatsnew.where(status: 0).limit(5).order(position: :asc).each_with_index do |w, index|
				f.write(					
					"<div class='contentdiv'>
					<div class='cropdiv'>
					<img style='width:165px;' src='" + "#{w.image}" + "' /></div><a href='#{w.link + '?whatsnew='}#{index + 1}'" + "> #{w.title} </a>" +
					"<div class='text'>" + "#{w.content}" + "</div>"  + "\n" +
					"<div class='fullstory'><a href='#{w.link + '?whatsnew='}#{index + 1}'> Full Story </a></div></div>")
				end

			uploader = FileUploader.new
			uploader.store!(f)  
		end     			
	end	

end

app/controllers/whatsnews_controller.rb
class WhatsnewsController < InheritedResources::Base
end

app/helpers/whatsnews_helper.rb
module WhatsnewsHelper
end

app/views/whatsnews/_form.html.erb
<%= form_for(@whatsnews) do |f| %>
  <% if @whatsnews.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@whatsnews.errors.count, "error") %> prohibited this whatsnews from being saved:</h2>

      <ul>
      <% @whatsnews.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/whatsnews/edit.html.erb
<h1>Editing whatsnews</h1>

<%= render 'form' %>

<%= link_to 'Show', @whatsnews %> |
<%= link_to 'Back', whatsnews_path %>

app/views/whatsnews/index.html.erb
<h1>Listing whatsnews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Content</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @whatsnews.each do |whatsnews| %>
      <tr>
        <td><%= whatsnews.title %></td>
        <td><%= whatsnews.image %></td>
        <td><%= whatsnews.content %></td>
        <td><%= whatsnews.link %></td>
        <td><%= link_to 'Show', whatsnews %></td>
        <td><%= link_to 'Edit', edit_whatsnews_path(whatsnews) %></td>
        <td><%= link_to 'Destroy', whatsnews, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Whatsnew', new_whatsnews_path %>

app/views/whatsnews/new.html.erb
<h1>New whatsnews</h1>

<%= render 'form' %>

<%= link_to 'Back', whatsnews_path %>

app/views/whatsnews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @whatsnews.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @whatsnews.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @whatsnews.content %>
</p>

<p>
  <strong>Link:</strong>
  <%= @whatsnews.link %>
</p>

<%= link_to 'Edit', edit_whatsnews_path(@whatsnews) %> |
<%= link_to 'Back', whatsnews_path %>