config/routes.rb
Rails.application.routes.draw do
  

  resources :images do
    collection do
      get :result
    end
  end

  root 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)


  
  resources :exports do
    collection do
      get :event
    end
  end

  resources :slides
  resources :releases
  resources :events
  resources :tips
  resources :settings

  resources :whatsnews

  resources :layouts
end

app/models/image.rb
class Image < ActiveRecord::Base

  mount_uploader :hero_thumb, PhotoUploader

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_thumb
  
  def crop_thumb
    hero_thumb.recreate_versions! if crop_x.present?
    # redirect_to root_url
  end

end

app/controllers/images_controller.rb
class ImagesController < InheritedResources::Base



    def update
    	@image = Image.find(params[:id])
    	if @image.update(image_params)
    		redirect_to result_images_url(id: @image.id)
    	end	
    	
    end

    def result
    	@image = Image.find(params[:id])
    end



  private
    def image_params
      params.require(:image).permit(:hero_thumb, :crop_x, :crop_y, :crop_w, :crop_h)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Hero Thumbnail" %><br>
    <%= f.file_field :hero_thumb %>
  </div>
  <div class="actions">
    <%= f.submit "Upload Image", class: 'btn' %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <thead>
    <tr>
      <th>Hero thumb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.hero_thumb %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<%= render 'form' %>

app/views/images/result.html.erb
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @image.hero_thumb.url(:thumb), :id => "preview" %>
	<p style="font-size: 13px;"><%= link_to 'Download', @image.hero_thumb.url(:thumb), :download =>  @image.hero_thumb.url(:thumb) %></p>

</div>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Crop Hero Image</h2>
<%= image_tag(@image.hero_thumb.large, :id => 'cropbox') %>


<h4>Preview</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @image.hero_thumb.url(:large), :id => "preview" %>
</div>


<%= form_for @image do |f| %>
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>
  <div class="actions">
    <%= f.submit "Crop" %>
  </div>
<% end %>