config/routes.rb
Rails.application.routes.draw do
  

  resources :images do
    collection do
      get :result
    end
  end

  root 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)


  
  resources :exports do
    collection do
      get :event
    end
  end

  resources :slides
  resources :releases
  resources :events
  resources :tips
  resources :settings

  resources :whatsnews

  resources :layouts
end

app/models/export.rb
class Export < ActiveRecord::Base

	belongs_to :layout
	belongs_to :tip
	belongs_to :whatsnew
	belongs_to :admin_user
	mount_uploader :link, FileUploader

	after_save :generate_arhiw_file, :unless => lambda { |entry| entry.tip_id.nil? }
	after_save :generate_arhiw, :unless => lambda { |entry| entry.tip_id.nil? }
	after_save :generate_file, :unless => lambda { |entry| entry.tip_id.nil? }
	after_save :generate_sidebar, :unless => lambda { |entry| entry.tip_id.nil? }
	after_save :generate_whats_new_content, :unless => lambda { |entry| entry.whatsnew_id.nil? }
	after_save :generate_whats_new, :unless => lambda { |entry| entry.whatsnew_id.nil? }


	# 2   scope :healthy_tips, -> { where('tip_id != ?', nil) }

	def self.healthy_tips
		where(whatsnew_id: nil)
	end

	def self.whats_news
		where(tip_id: nil)
	end

	def generate_whats_new
		File.open('default_third_column_home' + '.html', "w") do |f|     
			n = Nokogiri::HTML(open("https://s3-us-west-2.amazonaws.com/hhcheroku/uploads/whatsnew_content.html"))

				f.write(
					self.layout.body_top + "\n""\n""\n" +
					n.css('div.contentdiv').to_s + "\n""\n""\n" +
					self.layout.body_bottom
					)
			uploader = FileUploader.new
			uploader.store!(f)  
		end     			
	end


	def generate_whats_new_content
		File.open('whatsnew_content' + '.html', "w") do |f|     
				Whatsnew.all.each do |w|
				f.write(
					'<div class="contentdiv">' + "\n" +
					'<div class="cropdiv">' + "\n" +
					'<img style="width:165px;" src="' + w.image.to_s + '" /></div>'  + "\n" +
					'<a href="' +  w.try(:link) +'">' +  w.title + '</a>'  + "\n" +
					'<div class="text">' + w.try(:content) + '</div>'  + "\n" +
					'<div class="fullstory">' + "\n" +
					'<a href="' + w.link + '">' + 'Full Story </a>' + "\n" +
					'</div></div>'
					)
				end

			uploader = FileUploader.new
			uploader.store!(f)  
		end     			
	end	

	private

	def generate_arhiw_file
		File.open('arhiw' + '.html', "w") do |f|     

			Tip.all.each do |t|
				f.write('
					<div style="width: 690px; float:left;" class="tip"> 
						<div style="float: left; margin-right: 15px;">  '  + "\n" + 
							'<a href="' + t.try(:slug) + '.shtml">'  + "\n" + 
								'<img src="' + t.small_image.to_s + '" class="healthy-thumb">'  + "\n" +
							'</a>'  + "\n" +
						'</div>'  + "\n" +
						'<div>'  + "\n" +
						'<h3>' + "\n" +
							'<a href="' + t.try(:slug) + '.shtml">' + t.title + '</a>'  + "\n" +
						'</h3>'  + "\n" +
						'<p>' + t.short + '</p> ' + "\n" +
							'<a href="' + t.try(:slug) + '.shtml">' + "\n" +
								'<img src="../../images/healthy/learn-more.jpg" class="healthy-thumb">' + "\n" +
							'</a>' + "\n" +
						'</div>' + "\n" +
				'<br>' + "\n" +
                '<br> ' + "\n" +
					'</div>')
			end
			uploader = FileUploader.new
			uploader.store!(f)  
		end     	
	end


	def generate_file
		File.open(self.tip.slug + '.shtml', "w") do |f|     
			f.write(
				self.layout.head + "\n" +
				"<title>#{self.tip.title}</title>" + "\n" +
				'<meta property="og:title"' + ' content="' + "#{self.tip.title}" + '" />' + "\n" +
				'<meta property="og:description"' + ' content="' + "#{self.tip.short}" + '" />' + "\n" +
				'<meta property="og:image"' + ' content="' + "#{self.tip.imge_url}" + '" />' + "\n" +
				self.layout.body_top + "\n" +
				'<p class="heading2-article" style="display:none;">' + "#{self.tip.title}" + '</p>' + "\n" +
				'<img title="" border=0 alt="" align="center" src="' + "#{self.tip.imge_url}"  +'" id="pin" width="468" >' + "\n" +
				self.tip.content + "\n" +
				'<p class="dottedseparator">&nbsp;</p>' + "\n" +
				self.tip.tip_reference + "\n" +
				self.layout.tip_reference + "\n" +
				self.layout.body_bottom 
				)
			uploader = FileUploader.new
			uploader.store!(f)	
		end

	end

	def generate_sidebar
		File.open('stay-healthy-sidebar' + '.html', "w") do |f|     

			Tip.all.each do |t|
				f.write('
					<div style="border-bottom: 1px dotted #D6D6D6;">     
					<a href="' + t.try(:slug) + '.shtml">
					<img src="' + t.small_image.to_s + '" class="healthy-thumb">
					</a>
					<h3> 
					<a href="' + t.try(:slug) + '.shtml">' + t.title + '</a>
					</h3>
					</div>
					')
			end
			uploader = FileUploader.new
			uploader.store!(f)  
		end     	
	end


	def generate_arhiw
		layout = Layout.find(2)
		File.open('ForPatients-StayHealthy' + '.shtml', "w") do |f|     
			n = Nokogiri::HTML(open("https://s3-us-west-2.amazonaws.com/hhcheroku/uploads/arhiw.html"))

			f.write(
				layout.head + "\n" +
				layout.body_top + "\n" "\n""\n" +
				 n.css('div.tip').to_s + "\n""\n""\n" +
				layout.body_bottom
				)
			uploader = FileUploader.new
			uploader.store!(f)	

		end

	end


end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  before_action :set_export, only: [:show, :edit, :update, :destroy]
  def index
    @exports = Export.all
  end

  def show
      @export = Export.find(params[:id])
      @tip = @export.tip
  end

  def new
    @export = Export.new
  end

  def edit
  end




  def update
    respond_to do |format|
      if @export.update(export_params)
        format.html { redirect_to @export, notice: 'Export was successfully updated.' }
        format.json { render :show, status: :ok, location: @export }
      else
        format.html { render :edit }
        format.json { render json: @export.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @export.destroy
    respond_to do |format|
      format.html { redirect_to exports_url, notice: 'Export was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_export
      @export = Export.find(params[:id])
    end

    def export_params
      params.require(:export).permit(:title, :content, :link, :template, :layout_id, :tip_id)
    end
end

app/helpers/exports_helper.rb
module ExportsHelper
end

app/views/exports/_form.html.erb
<%= form_for(@export) do |f| %>
  <% if @export.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@export.errors.count, "error") %> prohibited this export from being saved:</h2>

      <ul>
      <% @export.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :layout %><br>
    <%= f.collection_select :layout_id, Layout.all, :id, :layout_name %>

  </div>
  <div class="field">
    <%= f.label :tips %><br>
    <%= f.collection_select :tip_id, Tip.order(:title), :id, :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :template %><br>
    <%= f.text_field :template %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exports/edit.html.erb
<h1>Editing export</h1>

<%= render 'form' %>

<%= link_to 'Show', @export %> |
<%= link_to 'Back', exports_path %>

app/views/exports/index.html.erb
<h1>Listing exports</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Content</th>
      <th>Template</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exports.each do |export| %>
      <tr>
        <td><%= export.title %></td>
        <td><%= export.link %></td>
        <td><%= export.content %></td>
        <td><%= export.template %></td>
        <td><%= link_to 'Show', export %></td>
        <td><%= link_to 'Edit', edit_export_path(export) %></td>
        <td><%= link_to 'Destroy', export, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Export', new_export_path %>

app/views/exports/new.html.erb
<h1>New export</h1>

<%= render 'form' %>

<%= link_to 'Back', exports_path %>

app/views/exports/show.html.erb
<p id="notice"><%= notice %></p>

<p>Your page is created. <%= link_to 'Click here to download.', root_url + @tip.slug + '.html'%>

  </p>